name: Build, Push, and Run Docker Image

on:
  push:
    branches:
      - main  # Adjust if using a different branch

jobs:
  build-push-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-app:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-app:latest

      - name: Run Docker Container
        run: docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/helloworld-app:latest
